name: Centauri Labs
description: Centauri Development Blog
meta_description: "Centauri Development Blog"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://blog.centauri.io'
google_analytics: 'UA-53407740-4'
disqus: true
disqus_shortname: 'centauri'

# Details for the RSS feed generator
url:            'http://blog.centauri.io'
author:         'Centauri Labs'
authorTwitter:  'rgawdzik'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
